version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_limited
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M

