server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      port: 6379
      host: localhost
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.hibernate: error
    file:
      name: logs/myapplication.log
    config: classpath:logback-spring.xml

  cloud:
    gateway:
      default-filters:
      # Tạm thời tắt RequestRateLimiter
      # - name: RequestRateLimiter
      #   args:
      #     redis-rate-limiter.replenishRate: 10
      #     redis-rate-limiter.burstCapacity: 20
      #     redis-rate-limiter.requestedTokens: 1
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: product-service
          predicates:
            - Path=/api/products/**
        - id: customer-service
          uri: customer-service
          predicates:
            - Path=/api/customers/**
        - id: order-service
          uri: order-service
          predicates:
            - Path=/orders/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true