services:
    mongo:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"
        healthcheck:
            test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 5s
            retries: 5

    nodeapp:
        build: .
        depends_on:
            mongo:
                condition: service_healthy
        ports:
            - "3000:3000"
        environment:
            - MONGO_URL=mongodb://mongo:27017

volumes:
    mongo-data:
